### ISSUE TITLE
utmps utmpx.h already includes utmps/utmpx.h

### ISSUE THREAD

**Issue by firasuke** [dslm4515/CMLFS#101]
This symlink is not needed as utmps's utmpx.h already includes `utmps/utmpx.h`.
https://github.com/dslm4515/CMLFS/blob/171f4ef4511578139416fdef1348b8dd3b1e4809/4-Final_System/013-utmps#L30

**Comment by dslm4515** [comment]
I can't remember what package it was, but it was looking for `/usr/include/utmpx.h`.

When I install utmps, this is what is installed:
```
└── usr
    ├── bin
    │   ├── utmps-utmpd
    │   ├── utmps-write
    │   └── utmps-wtmpd
    ├── include
    │   └── utmps
    │       ├── config.h
    │       ├── utmps.h
    │       └── utmpx.h
    └── lib
        ├── libutmps.a
        ├── libutmps.so -> libutmps.so.0.1
        ├── libutmps.so.0.1 -> libutmps.so.0.1.2.2
        └── libutmps.so.0.1.2.2

```
For now, I'll omit the link and see what package requires it

**Comment by firasuke** [comment]
> When I install utmps, this is what is installed:

I think you need to pass `--enable-libc-includes` to `utmps` configure in order to get `usr/include/utmpx.h`.

**Comment by dslm4515** [comment]
Thanks!

utmps build updated with commit fd8dffc891143757c941a9b5e0ef4b60068eef95

**Comment by firasuke** [comment]
You are welcome!
