### ISSUE TITLE
Libc++.so.1 (llvmtools) requires libatomic.so.1

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/CMLFS#12]
llvmtools' `libc++.so.1` from libcxx should NOT rely on `libatomic.so.1`, which is provided by GCC.

```
$ ldd /llvmtools/lib/libc++.so.1
        ldd (0x7fb67cb49000)
        libc.so => ldd (0x7fb67cb49000)
Error loading shared library libatomic.so.1: No such file or directory (needed by /llvmtools/lib/libc++.so.1)
        libunwind.so.1 => /llvmtools/lib/../lib/libunwind.so.1 (0x7fb67ca6b000)
        libc++abi.so.1 => /llvmtools/lib/../lib/libc++abi.so.1 (0x7fb67ca0f000)
```

This will require to build LLVM for llvmtools with a `LD_LIBARARY_PATH` hack

**Comment by owl4ce** [comment]
https://reviews.llvm.org/D43509?id=135044 ?

**Comment by owl4ce** [comment]
hmmmmmm
http://llvmweekly.org/issue/336

![image](https://user-images.githubusercontent.com/53987136/123536067-387df100-d752-11eb-9e28-6a35bf381a32.png)

**Comment by dslm4515** [comment]
Re-built `llvmtools` and made sure `libcxx` did not require libatomic.

now llvm/clang for `llvmtools` fails to build:

```
FAILED: include/llvm/IR/Attributes.inc 
cd /mnt/cmlfs/sources/llvm/build && /mnt/cmlfs/sources/llvm/build/bin/llvm-tblgen -gen-attrs -I /mnt/cmlfs/sources/llvm/include/llvm/IR -I /mnt/cmlfs/sources/llvm/build/include -I /mnt/cmlfs/sources/llvm/include /mnt/cmlfs/sources/llvm/include/llvm/IR/Attributes.td --write-if-changed -o include/llvm/IR/Attributes.inc -d include/llvm/IR/Attributes.inc.d
/bin/sh: /mnt/cmlfs/sources/llvm/build/bin/llvm-tblgen: No such file or directory
[220/3316] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/MsgPackDocument.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by dslm4515** [comment]
> hmmmmmm
> http://llvmweekly.org/issue/336
> 
> ![image](https://user-images.githubusercontent.com/53987136/123536067-387df100-d752-11eb-9e28-6a35bf381a32.png)

Looks like for libcxx, I’ll have to set a flag to disable libatomic

**Comment by owl4ce** [comment]
> > hmmmmmm
> > http://llvmweekly.org/issue/336
> > ![image](https://user-images.githubusercontent.com/53987136/123536067-387df100-d752-11eb-9e28-6a35bf381a32.png)
> 
> Looks like for libcxx, I’ll have to set a flag to disable libatomic

How?

**Comment by dslm4515** [comment]
Looks like I’ll have to patch `libcxx/cmake/Modules/CheckLibcxxAtomic.cmake`

**Comment by dslm4515** [comment]
Although it’s strange that after rebuilding `llvmtools`... llvmtools’ Libc++.so.1 no longer requires libatomic.

not sure if it matters that `PATH=/cgnutools/bin:/llvmtools/bin:/bin:/usr/bin`

**Comment by owl4ce** [comment]
Commenting this will disable libatomic detection for Linux.
`projects/libcxx/cmake/config-ix.cmake`
```sh
107 #  check_library_exists(atomic __atomic_fetch_add_8 "" LIBCXX_HAS_ATOMIC_LIB)
```

**Comment by owl4ce** [comment]
I think atomic detection is not from libcxx for the first time. Basically from libcxxabi? which produces atomic header.

**Comment by owl4ce** [comment]
I wonder how atomic detected when building libcxx

**Comment by dslm4515** [comment]
I probably will include a check for libunwind, libcxx, and libcxxabi to make sure there are no GCC dependencies. It’s annoying to finally build LLVM for llvmtools only to realize llvmtools has GCC dependencies.

**Comment by owl4ce** [comment]
Success
```sh
[ 99%] Built target clangStaticAnalyzerFrontend
make[2]: Entering directory '/mnt/cmlfs/sources/llvm/build'
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
make[2]: Entering directory '/mnt/cmlfs/sources/llvm/build'
[ 99%] Building C object tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o
[ 99%] Building CXX object tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/core_main.cpp.o
[100%] Linking CXX executable ../../../../bin/c-arcmt-test
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[100%] Built target c-arcmt-test
make[2]: Entering directory '/mnt/cmlfs/sources/llvm/build'
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
make[2]: Entering directory '/mnt/cmlfs/sources/llvm/build'
[100%] Linking CXX static library ../../../../lib/libclangFrontendTool.a
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[100%] Built target clangFrontendTool
make[2]: Entering directory '/mnt/cmlfs/sources/llvm/build'
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
make[2]: Entering directory '/mnt/cmlfs/sources/llvm/build'
[100%] Linking CXX static library ../../../../../lib/libclangDependencyScanning.a
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[100%] Built target clangDependencyScanning
[100%] Linking CXX executable ../../../../bin/c-index-test
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[100%] Built target c-index-test
```

**Comment by dslm4515** [comment]
> Commenting this will disable libatomic detection for Linux when configure libcxx (cmake).
> 
> ```shell
> check_library_exists(atomic __atomic_fetch_add_8 "" LIBCXX_HAS_ATOMIC_LIB)
> ```
> 
> `projects/libcxx/cmake/config-ix.cmake`
> 
> ```shell
> 102 else()
> 103   check_library_exists(pthread pthread_create "" LIBCXX_HAS_PTHREAD_LIB)
> 104   check_library_exists(m ccos "" LIBCXX_HAS_M_LIB)
> 105   check_library_exists(rt clock_gettime "" LIBCXX_HAS_RT_LIB)
> 106   set(LIBCXX_HAS_SYSTEM_LIB NO)
> 107 #  check_library_exists(atomic __atomic_fetch_add_8 "" LIBCXX_HAS_ATOMIC_LIB)
> 108 endif()
> ```

Closing issue as @owl4ce fixed issue
