### ISSUE TITLE
llvmtools/01-kernel-headers fails to build in glibc environment

### ISSUE THREAD

**Issue by andzai1995** [dslm4515/CMLFS#13]
That's may be the stupidiest bug, but who cares. When I try to make kernel headers via executing 
```
ARCH=${CMLFS_ARCH} LLVM=1 CC=clang CXX=clang++ make headers
```
this command fails with following error:
```  
HOSTCC  scripts/basic/fixdep
/bin/sh: line 1: scripts/basic/fixdep: No such file or directory
make[1]: *** [scripts/Makefile.host:95: scripts/basic/fixdep] Error 127
make[1]: *** Deleting file 'scripts/basic/fixdep'
make: *** [Makefile:536: scripts_basic] Error 2
```
This error doesn't appear in MLFS environment that's why I suggested to make minimal MLFS environment and then build CMLFS entirely.
How this bug could be fixed without creating of MLFS?

**Comment by owl4ce** [comment]
https://github.com/dslm4515/CMLFS/issues/10#issuecomment-869054170

**Comment by andzai1995** [comment]
> Try [#10 (comment)](https://github.com/dslm4515/CMLFS/issues/10#issuecomment-869054170)

Set HOSTCC. Exactly what I need. Thank you.

**Comment by owl4ce** [comment]
Yeah, `5.12.x` is so strange when using `LLVM=1`, HOSTCC always fail to build `fixdep.c`.

**Comment by andzai1995** [comment]
> Yeah, `5.12.x` is so strange when using `LLVM=1`, HOSTCC always fail to build fixdep.c.

I tried with 5.10.46, bug is present

**Comment by owl4ce** [comment]
> > Yeah, `5.12.x` is so strange when using `LLVM=1`, HOSTCC always fail to build fixdep.c.
> 
> I tried with 5.10.46, bug is present

Hmmmmmmmmmmmmmmm, I thought it only happened in `5.12.x` (based on what @dslm4515  said)

**Comment by andzai1995** [comment]
I didn't place make in command correctly. Now it works. I will check 3-chroot/005-kernel-headers, if this error will not appear, I will close this issue

**Comment by owl4ce** [comment]
well, so Linux can't live without GNU core concept
https://wiki.osdev.org/Target_Triplet

**Comment by dslm4515** [comment]
> > > Yeah, `5.12.x` is so strange when using `LLVM=1`, HOSTCC always fail to build fixdep.c.
> > 
> > 
> > I tried with 5.10.46, bug is present
> 
> Hmmmmmmmmmmmmmmm, I thought it only happened in `5.12.x` (based on what @dslm4515 said)

I forgot which kernel version, maybe 5.10.12, and bug isn’t present. It was worse when building the kernel with `LLVM=1` because of “assembler errors”... which was fixed with `LLVM_IAS=1`... I thought recent kernel versions had LLVM/Clang build support (before, there was a fork of the Linux kernel with focus on the LLVM build support)

**Comment by dslm4515** [comment]
Kernel 5.9.16 compiles fine without these errors or patches.
