### ISSUE TITLE
LLVM11: llvmtools: LLVM fails to build llvm-tblgen

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/CMLFS#14]
Re-built `llvmtools` and made sure `libcxx` did not require libatomic.

now llvm/clang for `llvmtools` fails to build:

```
FAILED: include/llvm/IR/Attributes.inc 
cd /mnt/cmlfs/sources/llvm/build && /mnt/cmlfs/sources/llvm/build/bin/llvm-tblgen -gen-attrs -I /mnt/cmlfs/sources/llvm/include/llvm/IR -I /mnt/cmlfs/sources/llvm/build/include -I /mnt/cmlfs/sources/llvm/include /mnt/cmlfs/sources/llvm/include/llvm/IR/Attributes.td --write-if-changed -o include/llvm/IR/Attributes.inc -d include/llvm/IR/Attributes.inc.d
/bin/sh: /mnt/cmlfs/sources/llvm/build/bin/llvm-tblgen: No such file or directory
[220/3316] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/MsgPackDocument.cpp.o
ninja: build stopped: subcommand failed.
```

_Originally posted by @dslm4515 in https://github.com/dslm4515/CMLFS/issues/12#issuecomment-869114868_

**Comment by dslm4515** [comment]
Added `-DLLVM_TABLEGEN=/cgnutools/bin/llvm-tblgen` to cmake command. Not sure if this will cause llvm binaries to have GCC dependencies.

So far build has surpassed 220 built targets!

**Comment by andzai1995** [comment]
> Added `-DLLVM_TABLEGEN=/cgnutools/bin/llvm-tblgen` to cmake command. Not sure if this will cause llvm binaries to have GCC dependencies.
> 
> So far build has surpassed 220 built targets!

Could you add a file "../files/libunwind-llvm12/compact_unwind_encoding.h" for libunwind in BMLFS repo, because I want to try build llvm 12 and catch errors, too.

**Comment by dslm4515** [comment]
> > Added `-DLLVM_TABLEGEN=/cgnutools/bin/llvm-tblgen` to cmake command. Not sure if this will cause llvm binaries to have GCC dependencies.
> > So far build has surpassed 220 built targets!
> 
> Could you add a file "../files/libunwind-llvm12/compact_unwind_encoding.h" for libunwind in BMLFS repo, because I want to try build llvm 12 and catch errors, too?

I actually have llvm12 working for bmlfs. Let me check which branch...

**Comment by dslm4515** [comment]
Ops. I forgot to extract the missing header from libunwind!

**Comment by andzai1995** [comment]
There is some code in file build-scripts/llvm12.build:
```
# Fix missing header for lld, https://bugs.llvm.org/show_bug.cgi?id=49228
mkdir -pv tools/lld/include/mach-o
cp -v ../files/libunwind-llvm12/compact_unwind_encoding.h tools/lld/include/mach-o
```
When I cloned BMLFS repo, this file is absent.

**Comment by dslm4515** [comment]
> There is some code in file build-scripts/llvm12.build:
> 
> ```
> # Fix missing header for lld, https://bugs.llvm.org/show_bug.cgi?id=49228
> mkdir -pv tools/lld/include/mach-o
> cp -v ../files/libunwind-llvm12/compact_unwind_encoding.h tools/lld/include/mach-o
> ```
> 
> When I cloned BMLFS repo, this file is absent.

Sorry. I’ll upload it

**Comment by andzai1995** [comment]
> > There is some code in file build-scripts/llvm12.build:
> > ```
> > # Fix missing header for lld, https://bugs.llvm.org/show_bug.cgi?id=49228
> > mkdir -pv tools/lld/include/mach-o
> > cp -v ../files/libunwind-llvm12/compact_unwind_encoding.h tools/lld/include/mach-o
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I cloned BMLFS repo, this file is absent.
> 
> Sorry. I’ll upload it

It is the same file like in $LLVMSRC/projects/libunwind/mach-o? Or this file is different?

**Comment by dslm4515** [comment]
I’ve uploaded the file to master branch of BMLFS

**Comment by dslm4515** [comment]
Now `clang-tblgen` is not built....

```
[1752/3316] Building StmtDataCollectors.inc...
FAILED: tools/clang/include/clang/AST/StmtDataCollectors.inc 
cd /mnt/cmlfs/sources/llvm/build && /mnt/cmlfs/sources/llvm/build/bin/clang-tblgen -gen-clang-data-collectors -I /mnt/cmlfs/sources/llvm/tools/clang/include/clang/AST -I /mnt/cmlfs/sources/llvm/tools/clang/include -I /mnt/cmlfs/sources/llvm/build/tools/clang/include -I /mnt/cmlfs/sources/llvm/build/include -I /mnt/cmlfs/sources/llvm/include /mnt/cmlfs/sources/llvm/tools/clang/include/clang/AST/StmtDataCollectors.td --write-if-changed -o tools/clang/include/clang/AST/StmtDataCollectors.inc -d tools/clang/include/clang/AST/StmtDataCollectors.inc.d
/bin/sh: /mnt/cmlfs/sources/llvm/build/bin/clang-tblgen: No such file or directory
[1753/3316] Building CXX object tools/ver...selistorder.dir/verify-uselistorder.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by owl4ce** [comment]
> There is some code in file build-scripts/llvm12.build:
> 
> ```
> # Fix missing header for lld, https://bugs.llvm.org/show_bug.cgi?id=49228
> mkdir -pv tools/lld/include/mach-o
> cp -v ../files/libunwind-llvm12/compact_unwind_encoding.h tools/lld/include/mach-o
> ```
> 
> When I cloned BMLFS repo, this file is absent.

no need

**Comment by dslm4515** [comment]
> Now `clang-tblgen` is not built....
> 
> ```
> [1752/3316] Building StmtDataCollectors.inc...
> FAILED: tools/clang/include/clang/AST/StmtDataCollectors.inc 
> cd /mnt/cmlfs/sources/llvm/build && /mnt/cmlfs/sources/llvm/build/bin/clang-tblgen -gen-clang-data-collectors -I /mnt/cmlfs/sources/llvm/tools/clang/include/clang/AST -I /mnt/cmlfs/sources/llvm/tools/clang/include -I /mnt/cmlfs/sources/llvm/build/tools/clang/include -I /mnt/cmlfs/sources/llvm/build/include -I /mnt/cmlfs/sources/llvm/include /mnt/cmlfs/sources/llvm/tools/clang/include/clang/AST/StmtDataCollectors.td --write-if-changed -o tools/clang/include/clang/AST/StmtDataCollectors.inc -d tools/clang/include/clang/AST/StmtDataCollectors.inc.d
> /bin/sh: /mnt/cmlfs/sources/llvm/build/bin/clang-tblgen: No such file or directory
> [1753/3316] Building CXX object tools/ver...selistorder.dir/verify-uselistorder.cpp.o
> ninja: build stopped: subcommand failed.
> ```

`clang-tblgen` **is built** but cannot execute...due to libraries not loading from `llvmtools/lib`:
```
$ LD_LIBRARY_PATH=/llvmtools/lib ldd   build/bin/clang-tblgen 
        /lib/ld-musl-x86_64.so.1 (0x7f75911d9000)
        libexecinfo.so.1 => /llvmtools/lib/libexecinfo.so.1 (0x7f7591038000)
        libc++.so.1 => /llvmtools/lib/libc++.so.1 (0x7f7590f6d000)
        libc++abi.so.1 => /llvmtools/lib/libc++abi.so.1 (0x7f7590f10000)
        libunwind.so.1 => /llvmtools/lib/libunwind.so.1 (0x7f7590efd000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f75911d9000)
```

perhaps, I should have added `LD_LIBRARY_PATH=/llvmtools/lib:/cgnutools/lib:/usr/lib:/lib` when compiling? Maybe `llvm-tblgen` would have been built too?

**Comment by owl4ce** [comment]
is this issue related to build llvm in llvmtools?

**Comment by owl4ce** [comment]
> is this issue related to build llvm in llvmtools?

For LLVM 12, I just fine. See https://github.com/dslm4515/CMLFS/issues/12#issuecomment-869230916

**Comment by dslm4515** [comment]
> is this issue related to build llvm in llvmtools?

yes for llvm11 (master). First build fails after 4mins for `llvm-tblgen` not built or unable to execute. So i reconfigured with using `llvm-tblgen` from `cgnutools`. Build progresses for 58mins then fails on unable to execute built `clang-tblgen`

**Comment by dslm4515** [comment]
> > is this issue related to build llvm in llvmtools?
> 
> For LLVM 12, I just fine while building. See [#12 (comment)](https://github.com/dslm4515/CMLFS/issues/12#issuecomment-869230916)
> 
> Now moving to chroot steps. I'll report if an issue appeared.

Before you were contributing, i was working on LLVM12 branch...lol, but i was stuck on libcxx of llvmtools (by now, you, and others already fixed that). I thought i'd work on master (llvm11) to have it updated with latest software versions of June 18th 2021.

Hopefully, no GCC dependencies for `llvmtools`!

**Comment by owl4ce** [comment]
> > > is this issue related to build llvm in llvmtools?
> > 
> > 
> > For LLVM 12, I just fine while building. See [#12 (comment)](https://github.com/dslm4515/CMLFS/issues/12#issuecomment-869230916)
> > Now moving to chroot steps. I'll report if an issue appeared.
> 
> Before you were contributing, i was working on LLVM12 branch...lol, but i was stuck on libcxx of llvmtools (by now, you, and others already fixed that). I thought i'd work on master (llvm11) to have it updated with latest software versions of June 18th 2021.
> 
> Hopefully, no GCC dependencies for `llvmtools`!

I just looking for your build, I don't want to contribute for my concept. Maybe just for fixing an issues 😄

**Comment by owl4ce** [comment]
I use make for LLVM, so mostly never install ninja (and less dependencies) until entering chroot.

**Comment by dslm4515** [comment]
> I use GNU Make for LLVM, so mostly never install ninja (and less dependencies) until entering chroot (meson).

Good point. I like ninja for the clean text output... although, make can do that too.

Make is pretty common and less dependencies, i'd likely switch from ninja to make

**Comment by owl4ce** [comment]
> > I use GNU Make for LLVM, so mostly never install ninja (and less dependencies) until entering chroot (meson).
> 
> Good point. I like ninja for the clean text output... although, make can do that too.
> 
> Make is pretty common and less dependencies, i'd likely switch from ninja to make

Rights, Ninja can show total of source code and not showing enter-close directory like Make.

**Comment by dslm4515** [comment]
> I use GNU Make for LLVM, so mostly never install ninja (and less dependencies) until entering chroot (meson). I'm prefer [Samurai](https://github.com/michaelforney/samurai).
> 
> _May I ask. What packages that requires meson?_

Samurai looks good. I do hate how ninja is either built with python or cmake. I may replace ninja with samurai in both CMLFS and MLFS.

For CMLFS, meson is not used. It is built so that a CMLFS system can build packages that use meson as their build system.... I forgot the original reason meson was added to LFS.

**Comment by owl4ce** [comment]
> For CMLFS, meson is not used. It is built so that a CMLFS system can build packages that use meson as their build system.... I forgot the original reason meson was added to LFS.

I think so!

**Comment by owl4ce** [comment]
In Appendix, showing will be used when building Systemd.

**Comment by owl4ce** [comment]
Try
https://github.com/zlib-ng/zlib-ng

**Comment by dslm4515** [comment]
> Try this
> https://github.com/zlib-ng/zlib-ng

I noticed hasn't been updated for a while. I suppose i'll switch to zlib-ng, just like how i dropped pkg-config for pkgconf

**Comment by owl4ce** [comment]
and maybe pigz instead of gzip, but pigz requires zlib (zlib-ng works too).

**Comment by dslm4515** [comment]
I'm closing this as I don't think anyone will want to build LLVM-11 for CMLFS.
