### ISSUE TITLE
Alternate Packages

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/CMLFS#16]
And maybe pigz instead of gzip, but pigz requires zlib (zlib-ng works too). Cons: pigz doesn't have wrapper script such as for grep (zgrep). Can be installed for both, gzip just for wrapper script  if needed 😄 lol

_Originally posted by @owl4ce in https://github.com/dslm4515/CMLFS/issues/14#issuecomment-869789668_

**Comment by dslm4515** [comment]
So far....
Ninja -> Samurai
zlib -> zlib-ng
gzip -> pigz
pkg-config -> pkgconf [done]

**Comment by owl4ce** [comment]
And when prefer to build CMLFS with *BSD portable libraries instead of GNU 😸

**Comment by dslm4515** [comment]
@owl4ce how about gettext-tiny? Sometimes, autotools (autoconf+automake+m4+etc] run fine for regenerating configure for coreutils ... other times it fails. Have you had any similar experiences?

**Comment by owl4ce** [comment]
> @owl4ce how about gettext-tiny? Sometimes, autotools (autoconf+automake+m4+etc] run fine for regenerating configure for coreutils ... other times it fails. Have you had any similar experiences?

Yes, its works like a charm 👍🏻

**Comment by owl4ce** [comment]
But sorry, I use toybox for replacing some packages e.g `file`, `findutils`, `coreutils`, `tar`, `sed`, `grep`. `diffutils` and `patch` are still GNU because of compability (powerful).

**Comment by dslm4515** [comment]
> In my concepts, I was trying to build with less GNU utils and libraries lol smile

I may start another repo with that as the purpose

I did rebuild `llvmtools` to replace Ninja with Samurai to drop `libffi` and `python3`. Definitely made llvmtools smaller:

python3+libffi+ninja: ~ 140Mb ( .tar.xz )
Samurai + no python3 + no libffi + no ninja: ~ 116Mb ( .tar.xz )

**Comment by dslm4515** [comment]
> I did rebuild llvmtools to replace Ninja with Samurai to drop libffi and python3

Libcxxabi requires python. Definately need to add libffi + python3 to llvmtools

**Comment by dslm4515** [comment]
Looks like zlib-ng (with zlib-compat)  isn't compatible with perl? 

Perl fails to build:
```
In file included from Zlib.xs:34:
/usr/include/zlib.h:1781:31: error: unknown type name 'gzFile'
Z_EXTERN int Z_EXPORT gzgetc_(gzFile file);  /* backward compatibility */
                              ^
/usr/include/zlib.h:1818:13: error: unknown type name 'gzFile'
   Z_EXTERN gzFile Z_EXPORT gzopen(const char *, const char *);
            ^
/usr/include/zlib.h:1819:45: error: unexpected type name 'off_t': expected identifier
   Z_EXTERN z_off_t Z_EXPORT gzseek(gzFile, z_off_t, int);
                                            ^
/usr/include/zconf.h:159:21: note: expanded from macro 'z_off_t'
#    define z_off_t off_t
                    ^
In file included from Zlib.xs:34:
/usr/include/zlib.h:1819:54: error: expected identifier
   Z_EXTERN z_off_t Z_EXPORT gzseek(gzFile, z_off_t, int);
                                                     ^
/usr/include/zlib.h:1820:37: error: a parameter list without types is only allowed in a function definition
   Z_EXTERN z_off_t Z_EXPORT gztell(gzFile); 
                                    ^
/usr/include/zlib.h:1821:39: error: a parameter list without types is only allowed in a function definition
   Z_EXTERN z_off_t Z_EXPORT gzoffset(gzFile);   
                                      ^
/usr/include/zlib.h:1840:35: error: unknown type name 'gzFile'
Z_EXTERN int Z_EXPORTVA gzvprintf(gzFile file, const char *format, va_list va);
                                  ^
In file included from Zlib.xs:743:
./constants.h:370:18: warning: incompatible pointer to integer conversion assigning to 'IV' (aka 'long') from 'void *' [-Wint-conversion]
      *iv_return = Z_NULL;
                 ^ ~~~~~~
```

**Comment by owl4ce** [comment]
Autoconf fails using OpenBSD M4 (Ibara's)
```sh
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-musl
checking host system type... x86_64-pc-linux-musl
configure: autobuild project... GNU Autoconf
configure: autobuild revision... 2.71
configure: autobuild hostname... localh3art
configure: autobuild timestamp... 20210706T073551Z
checking for a shell whose -n mode is known to work... /bin/sh
checking for characters that cannot appear in file names... none
checking whether directories can have trailing spaces... yes
checking for expr... /usr/bin/expr
checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH.
GNU M4 1.4.6 or later is required; 1.4.16 or newer is recommended.
GNU M4 1.4.15 uses a buggy replacement strstr on some systems.
Glibc 2.9 - 2.12 and GNU M4 1.4.11 - 1.4.15 have another strstr bug.
```

**Comment by owl4ce** [comment]
> Autoconf fail to configure using OpenBSD M4 (Ibara's)
> 
> ```shell
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking build system type... x86_64-pc-linux-musl
> checking host system type... x86_64-pc-linux-musl
> configure: autobuild project... GNU Autoconf
> configure: autobuild revision... 2.71
> configure: autobuild hostname... localh3art
> configure: autobuild timestamp... 20210706T073551Z
> checking for a shell whose -n mode is known to work... /bin/sh
> checking for characters that cannot appear in file names... none
> checking whether directories can have trailing spaces... yes
> checking for expr... /usr/bin/expr
> checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH.
> GNU M4 1.4.6 or later is required; 1.4.16 or newer is recommended.
> GNU M4 1.4.15 uses a buggy replacement strstr on some systems.
> Glibc 2.9 - 2.12 and GNU M4 1.4.11 - 1.4.15 have another strstr bug.
> ```

fixed by defining `M4`
```sh
M4=/usr/bin/m4 ./configure --prefix=/usr 
```

**Comment by owl4ce** [comment]
But.. build fails caused by autom4te that still needs GNU M4

**Comment by owl4ce** [comment]
https://github.com/openbsd/ports/tree/master/devel/autoconf/2.71

**Comment by owl4ce** [comment]
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Why-GNU-M4.html

**Comment by dslm4515** [comment]
> **But.. build fails caused by autom4te that still needs GNU M4.**

Looks like autom4te has to be patched for Ibara's M4

**Comment by dslm4515** [comment]
I have not gotten around to porting `gettext-tiny` from simple Makefiles to a build system generated by GNU's autotools. _The current source of `gettext-tiny` does not use libtool... i think i ran into a problem 1-2 years ago where a package required some sort of library archive or file made from libtool with `gettext-tiny` source._

I may reconsider using a different build/configure system if autotools are hard coded for GNU's autotools (M4, autoconf, automake, etc.)

**Comment by dslm4515** [comment]
I'll move this to discussions
