### ISSUE TITLE
Could we have a more "friendly" license in this?

### ISSUE THREAD

**Issue by takusuman** [dslm4515/CMLFS#2]
As i've seen, this isn't licensed formally yet, so i was going to suggest that we use something like the z-lib license for plain-text documentation.
I think that a more copycenter license would help when linking/using content from here in something licensed under a liberal license, like a Wiki licensed under CC-BY, for example.

Sorry for any broken english, i'm still praticing it.

**Comment by dslm4515** [comment]
I haven't looked into licensing yet. I also don't remember what the default is for github. I made my repository locally and uploaded to github as means of backup, portability and sharing with who ever is interested in my work.

**Comment by luiztheblues** [comment]
> I made my repository locally and uploaded to github as means of backup, portability and sharing with who ever is interested in my work.

Well, that's the spirit of open source!

**Comment by dslm4515** [comment]
How about:

GNU General Public License v3.0 ?

I just want a license such that anyone can share & modify code, as long as credit is given. BUT i do not want my work used in closed-source projects and I do not want to be liable for warranties (my work is a result of passion and not for making money)

**Comment by owl4ce** [comment]
> How about:
> 
> GNU General Public License v3.0 ?
> 
> I just want a license such that anyone can share & modify code, as long as credit is given. BUT i do not want my work used in closed-source projects and I do not want to be liable for warranties (my work is a result of passion and not for making money)

I think suitable with MIT or BSD clause-2.

**Comment by owl4ce** [comment]
https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633

**Comment by dslm4515** [comment]
> I think suitable with MIT or BSD-2-Clause.

Now that I think about it, why should I worry... say if a company commercializes CMLFS into a OS for profit? From what i understand, GNU GPL3 requires that if CMLFS is used in another project, that project has to be licensed under GNU GPL3.

I suppose I would go for GNU GPL3 if wrote all the source code myself :P

**Comment by owl4ce** [comment]
Just choose the one that suits with you.

**Comment by dslm4515** [comment]
MIT it is.

**Comment by takusuman** [comment]
> 
> 
> > I think suitable with MIT or BSD-2-Clause.
> 
> Now that I think about it, why should I worry... say if a company commercializes CMLFS into a OS for profit? From what i understand, GNU GPL3 requires that if CMLFS is used in another project, that project has to be licensed under GNU GPL3.
> 
> I suppose I would go for GNU GPL3 if wrote all the source code myself :P

I think that, for documentation, CC-BY 4.0 would fit perfectly.
Now, for code, i think GPL v2 would be nice; it's the same license that Linux itself and it's largely used, unlike GPL v3 which is a relatively recent license.
