### ISSUE TITLE
Minor bugs & mistakes

### ISSUE THREAD

**Issue by andzai1995** [dslm4515/CMLFS#24]
Let's put in this issue that bugs like misplacing in configure scripts, misplacing of files, patches, etc. In general, everything of that should be fixed by maintainer not in first turn and you can fix it temporarly by yourselves. But in the end it must be fixed.
1. 3-chroot/34-flex. In configure script HELPMAN equals to /tools/bin/true, but in CMLFS we don't use it. HELPMAN should be equal to /llvmtools/bin/true.

**Comment by dslm4515** [comment]
>3-chroot/34-flex. In configure script HELPMAN equals to /tools/bin/true, but in CMLFS we don't use it. HELPMAN should be equal to /llvmtools/bin/true.

fixed with 51c237f

**Comment by dslm4515** [comment]
Branch llvm-12.0.0 is currently incomplete, as i did not take note of the changes i made to build GCC & binutils to install in `/llvmtools` and `/usr` instead of `/llvmtools/gnu` and `/opt/gnu`. I was expecting GCC to fail to compile in chroot, but it didn't.

I am doing another build to record changes and catch mistakes

**Comment by dslm4515** [comment]
Is there any reason to keep the master branch on LLVM-11.0.0? I'm thinking of dropping it or making a separate branch.

**Comment by owl4ce** [comment]
Use LLVM 12 as default.

**Comment by dslm4515** [comment]
> Use LLVM 12 as default. thinking

I think i will, since i have been working on CMLFS with LLVM-12 for the past few weeks.

**Comment by dslm4515** [comment]
I moved the master branch to a new branch, LLVM-11.0.0 ... i get that working later.

Once I finish another build, _This time uploading my build commands,_ I will update the master to the `llvm-12.0.0` branch. The llvm-12.0.0 branch will considered  as CMLFS 2.0

**Comment by andzai1995** [comment]
Second minor bug. What libtool should we use (from clang 12 or gnu variant?)
![Снимок экрана от 2021-07-06 21-22-40](https://user-images.githubusercontent.com/10092024/124649037-a6d45900-dea0-11eb-8d76-0d3f1639d5f5.png)

**Comment by dslm4515** [comment]
> Second minor bug. What libtool should we use (from clang 12 or gnu variant?)

Try libtool from clang (LLVM-12). Unofficially, i would like to use tools from LLVM over GNU tools

**Comment by dslm4515** [comment]
I'll close this and re-open if there are more minor typos, bugs, or mistakes.

Otherwise, i enabled Discussions for this repo
