### ISSUE TITLE
llvmtools: Failed to build Cmake under Glibc #19

### ISSUE THREAD

**Issue by muhammaddzaky** [dslm4515/CMLFS#25]
![5](https://user-images.githubusercontent.com/58392246/124932641-72da6e80-e02d-11eb-95af-d067f1a9a44f.jpg)
...

[ 28%] Building C object Source/kwsys/CMakeFiles/cmsysTestSharedForward.dir/testSharedForward.c.o
[ 28%] Building C object Source/kwsys/CMakeFiles/cmsysTestsC.dir/testEncode.c.o
[ 28%] Building C object Source/kwsys/CMakeFiles/cmsysTestsC.dir/cmsysTestsC.c.o
[ 29%] Building C object Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/archive_acl.c.o
[ 29%] Building C object Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/archive_check_magic.c.o
In file included from /mnt/cmlfs/sources/pkgs/cmake-3.20.5/Utilities/cmlibarchive/libarchive/archive_acl.c:37:
/usr/include/wchar.h:600:9: error: unknown type name '__gnuc_va_list'
                      __gnuc_va_list __arg)
                      ^
/usr/include/wchar.h:607:8: error: unknown type name '__gnuc_va_list'
                     __gnuc_va_list __arg)
                     ^
/usr/include/wchar.h:613:9: error: unknown type name '__gnuc_va_list'
                      __gnuc_va_list __arg)
                      ^
/usr/include/wchar.h:675:8: error: unknown type name '__gnuc_va_list'
                     __gnuc_va_list __arg)
                     ^
/usr/include/wchar.h:682:7: error: unknown type name '__gnuc_va_list'
                    __gnuc_va_list __arg)
                    ^
/usr/include/wchar.h:687:8: error: unknown type name '__gnuc_va_list'
                     __gnuc_va_list __arg)
                     ^
/usr/include/wchar.h:698:7: error: unknown type name '__gnuc_va_list'
                                  __gnuc_va_list __arg), __isoc99_vfwscanf)
                                  ^
/usr/include/wchar.h:701:6: error: unknown type name '__gnuc_va_list'
                                 __gnuc_va_list __arg), __isoc99_vwscanf)
                                 ^
/usr/include/wchar.h:705:11: error: unknown type name '__gnuc_va_list'
                                      __gnuc_va_list __arg), __isoc99_vswscanf)
                                      ^

... so many errors here ...
I don't know how to override headers PATH to /llvmtools/include, when I try to configure with CFLAGS="-I/llvmtools/include" CXXFLAGS="-I/llvmtools/include" ./bootstrap still fails to build.

**Comment by dslm4515** [comment]
Check issue https://github.com/dslm4515/CMLFS/issues/19

**Comment by owl4ce** [comment]
> Check issue #19

Help report this accout, this is bot.

**Comment by dslm4515** [comment]
> Help report creator of this issue account, that's bot.

Explains the unrelated picture posted with a  unrelated picture

**Comment by owl4ce** [comment]
> > Help report creator of this issue account, that's bot.
> 
> Explains the unrelated picture posted with a unrelated picture

Check his account.
