### ISSUE TITLE
extra/alt: llvm-12 fails to compile with netbsd-curses at stage 8 of cgnutools

### ISSUE THREAD

**Issue by takusuman** [dslm4515/CMLFS#42]
I was compiling llvm and then i got this error:
![2021-09-12-224038_1013x672_scrot](https://user-images.githubusercontent.com/47103338/133011870-a4423876-fc5f-4e06-8177-bd17487af3b3.png)
Full text log: https://termbin.com/eibv
As you can see, it's trying to "call"/link to `libc.so.6` from the host system, not the toolchain one.
So, just to be sure, i ran `ldd` both from the toolchain and from the host just to see where exactly libterminfo.so was trying to link:
![2021-09-12-225110_1003x179_scrot](https://user-images.githubusercontent.com/47103338/133012481-06f693c5-dabc-4b2d-80a5-3b06515851f0.png)
And yes; apparently, when i built netbsd-curses, it was linked to the wrong libc.

I'm not sure if i will fix this right now -- it's late and i have to study and work tomorrow -- , so take this as a reminder and as an advice.

**Comment by dslm4515** [comment]
Ugh. I always have issues with ncurses. Even back then when developing MLFS. For my first experimental build of CMLFS, I mysteriously built cgnutools _without_ ncurses. I could never find out why as every other attempt, I had to build ncurses.

luckily, one can use patchelf to fix/change dependencies in built libraries. A quick and dirty way to force a toolchain to work, but I prefer not.

I admit, I did use different flags for ncurses in Optimux. I can’t remember off the top of my head if it’s was only for the final system in chroot or in one of the tools chains

**Comment by takusuman** [comment]
> Ugh. I always have issues with ncurses. Even back then when developing MLFS. For my first experimental build of CMLFS, I mysteriously built cgnutools _without_ ncurses. I could never find out why as every other attempt, I had to build ncurses.

Yeah, i understand your pain. I've been experimenting with *MLFS since January and *always* ncurses was giving errors in some part of the process.

> luckily, one can use patchelf to fix/change dependencies in built libraries. A quick and dirty way to force a toolchain to work, but I prefer not.

I think it's better to just clean the toolchain and recompile it with the correct settings.
For now, i will just be building an experimental toolchain for my hobby-distro, so i'm really not worried about using GNU ncurses instead of netbsd-curses.

> I admit, I did use different flags for ncurses in Optimux. I can’t remember off the top of my head if it’s was only for the final system in chroot or in one of the tools chains

Don't worry about that for now. :^)
May some people can solve this problem with netbsd-curses, so let's keep this issue open.

**Comment by owl4ce** [comment]
Hmm, mine is fine using netbsd-curses .. 🤔

**Comment by takusuman** [comment]
> Hmm, mine is fine using netbsd-curses .. thinking

Could you share with us the `config.mak` or you've used that which i wrote at [extra/alt/cgnutools_7a-netbsd-curses](https://github.com/dslm4515/CMLFS/blob/master/extra/alt/cgnutools_7a-netbsd-curses)?

What are your `CFLAGS` too? I don't remember exactly what i was using but it wasn't not that could harm the process in fact, i think.

**Comment by takusuman** [comment]
BTW, removed netbsd-curses and built GNU ncurses on its place; trying to compile clang right now.

**Comment by owl4ce** [comment]
> Could you share with us the `config.mak` or you've used that which i wrote at [extra/alt/cgnutools_7a-netbsd-curses](https://github.com/dslm4515/CMLFS/blob/master/extra/alt/cgnutools_7a-netbsd-curses)?

Sure. I only build dynamic library and the program binaries.
```sh
# Build.
time { make CC="${CMLFS_TARGET}-gcc" all-dynamic; }

# Install.
time { make PREFIX=/cgnutools install-dynamic; }
```

**Comment by takusuman** [comment]
> BTW, removed netbsd-curses and built GNU ncurses on its place; trying to compile clang right now.

And got the same error when linking to `libterminfo.so`.
![2021-09-13-035319_1014x688_scrot](https://user-images.githubusercontent.com/47103338/133037277-e04318b1-579c-4160-8718-7cf93999a9e1.png)

May i will need to rebuild all my toolchain? 🤷🏽‍♂️ 😕

**Comment by takusuman** [comment]
> > Could you share with us the `config.mak` or you've used that which i wrote at [extra/alt/cgnutools_7a-netbsd-curses](https://github.com/dslm4515/CMLFS/blob/master/extra/alt/cgnutools_7a-netbsd-curses)?
> 
> Sure. I only built dynamic libraries and the program binaries.
> 
> ```shell
> # Build.
> time { make CC="${CMLFS_TARGET}-gcc" all-dynamic; }
> 
> # Install.
> time { make PREFIX=/cgnutools install-dynamic; }
> ```

Nice, i was doing `all`.
May i edit that later.

**Comment by takusuman** [comment]
Well, may the problem is just mine.
I will try to rebuild the entire toolchain, if i got any progress i will update this issue.

**Comment by takusuman** [comment]
I'm not sure, but i think i figured out what happened.
I didn't unset'd `LDFLAGS` after 5-GCC-final, so may this is the cause to ncurses being mislinked.

**Comment by dslm4515** [comment]
> Hmm, mine is fine using netbsd-curses .. 🤔

I’d say this the curse of ncurses!

**Comment by takusuman** [comment]
Well, in fact, i think i've discovered the real problem here.
When i was compiling LLVM (*and* ncurses), i was trying to `ld` it to the host and not to the `/cgnutools` toolchain.
That was solved (at least i think, i'm compiling LLVM now with @owl4ce's last patch to remove ncurses dependency) using `LDFLAGS="-Wl,-rpath,/cgnutools/lib"`, which was referenced before at the 25th line in 5-GCC-final.

I don't know if it's my host's (Arch Linux with LTS kernel) problem or if the docs are wrong in don't exporting `LDFLAGS`.

If you guys have any objection to this, just say. I'm closing this issue.

**Comment by owl4ce** [comment]
> When i was compiling LLVM (_and_ ncurses), i was trying to `ld` it to the host and not to the `/cgnutools` toolchain.

@takusuman 

So strange, the GCC in the `cgnutools` should invoke the linker to links againts `/cgnutools/lib/ld-musl-x86_64.so.1`.
https://github.com/dslm4515/CMLFS/blob/1b8e2d734003e3dc84dc3f7656cef4fd1c08c6b1/1-cgnutools/5-GCC-final#L53-L70

**Comment by takusuman** [comment]
> > When i was compiling LLVM (_and_ ncurses), i was trying to `ld` it to the host and not to the `/cgnutools` toolchain.
> 
> @takusuman
> 
> So strange, the GCC in the `cgnutools` should invoke the linker to links againts `/cgnutools/lib/ld-musl-x86_64.so.1`.
> 
> https://github.com/dslm4515/CMLFS/blob/1b8e2d734003e3dc84dc3f7656cef4fd1c08c6b1/1-cgnutools/5-GCC-final#L53-L70
> 
> Also .. in my builds, I don't use these stuffs. The last, I only use `make` command.
> 
> https://github.com/dslm4515/CMLFS/blob/1b8e2d734003e3dc84dc3f7656cef4fd1c08c6b1/1-cgnutools/5-GCC-final#L25
> 
> https://github.com/dslm4515/CMLFS/blob/1b8e2d734003e3dc84dc3f7656cef4fd1c08c6b1/1-cgnutools/5-GCC-final#L47-L48

Well, and it was, at least the dummy.c that i compiled at this step was linked to cgnutools' libc; but for some reason, after file, it was trying to link to host's libc.
That's weird, ***really*** weird.
Well, let's see if LLVM will work anyway.

**Comment by takusuman** [comment]
Btw, i'll reopen as this can be a really interesting discussion.

**Comment by owl4ce** [comment]
> Btw, i'll reopen as this can be a really interesting discussion.

Should migrate to discussion tab. 😄

**Comment by takusuman** [comment]
> > Btw, i'll reopen as this can be a really interesting discussion.
> 
> Should migrate to discussion tab. smile

How could i do this? 🧐 
Although using GitHub since 2019, i still don't know how to use some features.

**Comment by owl4ce** [comment]
> How could i do this? 🧐

Only maintainer can do that, otherwise you can start a new discussion.

**Comment by takusuman** [comment]
> > How could i do this? monocle_face
> 
> Only maintainer can do that, otherwise you can start a new [discussion](https://github.com/dslm4515/CMLFS/discussions).

Well, may @dslm4515 could do this for us. 😃
