### ISSUE TITLE
Section 0-Preparation -  TRUPLE phrase, may be TRIPLE?

### ISSUE THREAD

**Issue by Cerberios** [dslm4515/CMLFS#58]
Hello there!
First of all, thank You for great tutorial.

Please, look over - https://github.com/dslm4515/CMLFS/blob/master/0-Preparation
Line 98 and 109; seems there misprint occur - TRUPLE phrase, may be TRIPLE?
Please, fix! Thanks!

**Comment by Cerberios** [comment]
Also, please look over data below. Section 2-llvmtools/07-clang-llvm

# Set the truples...
export CONFIG_TRUPL**ES+="-**DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-pc-linux-musl " 
export  CONFIG_TRUPL**ES="-**DLLVM_HOST_TRIPLE=x86_64-cmlfs-linux-musl " 
export  CONFIG_TRUPL**ES="-**DCOMPILER_RT_DEFAULT_TARGET_TRIPLE=x86_64-pc-linux-musl " 

Question: why there symbol "+" not available for string 2 and 3? IMO, in such case this variable will be redefined?
And for config will be passed only one param instead of 3?
Please fix in case it is misprint. Thanks!

**Comment by dslm4515** [comment]
Truple: Originally, I mistyped "tuple" [source](https://wiki.debian.org/Multiarch/Tuples)

So yes, technically it should be `tuple` and not `truple\triple`.

Here are some examples:

`$triplet=i686-linux-gnu`

`$tuple=i686-pc-linux-musl`

**Comment by dslm4515** [comment]
I replaced all instances of `TRUPLE` with `TUPLE`

Commit 61ac68e
