### ISSUE TITLE
In section 2-llvmtools/07-clang-llvm - missed "s"  (Line 136-138) 

### ISSUE THREAD

**Issue by Cerberios** [dslm4515/CMLFS#59]
In section 2-llvmtools/07-clang-llvm
(Line 136-138) 

Remove the LLVM source as it will not be needed until chroot
cd $CMLFS/source && \
rm -rf llvm

Actual: seems symbol "s" missed, 
Expected: Initially at preparation stage it was "sourceS' folder name

**Comment by dslm4515** [comment]
Fixed in commit  39ed7a7
