### ISSUE TITLE
Section 1-cgnutools/6a-libexecinfo - why cc small (not a CC)

### ISSUE THREAD

**Issue by Cerberios** [dslm4515/CMLFS#63]
1-cgnutools/6a-libexecinfo

Please look over line 10-11 - there defined compiler, correct?
But cc != CC for Linux, so command may be mis-interpreted.
Please, check and fix as well. Thanks!

**Comment by andzai1995** [comment]
It was a mistake. Correct version is CC, of course

**Comment by dslm4515** [comment]
Fixed in commit 69520734c207ee9e76cb52f32f57c98eb323054f
