### ISSUE TITLE
Section 3-chroot/072-grub - need check mess in re-link (needed as.gnu also)

### ISSUE THREAD

**Issue by Cerberios** [dslm4515/CMLFS#64]
In section 3-chroot/072-grub
--
Build still tries to use clang. Temporarily switch to GCC
mv -v /usr/bin/{gcc,gcc.clang}
ln -sv gcc.gnu /usr/bin/gcc
--
There a little mess.
1) It shows "/usr/bin/gcc - no such file"
Need to add  ln -sv gcc.gnu /usr/bin/gcc
2) Reg. this instruction, configure fails with "wrong assembler" - it looking at "as from clang", not GNU
I added ln -sv /usr/bin/as.gnu /usr/bin/as
After these fixes configuration and compile OK

**Comment by andzai1995** [comment]
Read https://github.com/dslm4515/CMLFS/issues/23
