### ISSUE TITLE
llvm compilation error.

### ISSUE THREAD

**Issue by PandemRus** [dslm4515/CMLFS#67]
llvm compilation error. All steps are made in accordance with the instructions. At the stage CMLFS / 1-cgnutools / 7-clang gives an error.

[ 17%] Building CXX object utils/not/CMakeFiles/not.dir/not.cpp.o
[ 17%] Built target LLVMBitstreamReader
[ 17%] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/Minidump.cpp.o
[ 17%] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/MsgPackDocument.cpp.o
[ 17%] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/MsgPackDocumentYAML.cpp.o
[ 17%] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/MsgPackReader.cpp.o
[ 17%] Linking CXX executable ../../bin/not
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: warning: libc.so.6, needed by /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1, not found (try using -rpath or -rpath-link)
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `__stack_chk_fail@GLIBC_2.4'
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `strlen@GLIBC_2.2.5'
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `dladdr@GLIBC_2.34'
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `free@GLIBC_2.2.5'
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `realloc@GLIBC_2.2.5'
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `malloc@GLIBC_2.2.5'
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `snprintf@GLIBC_2.2.5'
/mnt/cmlfs/cgnutools/bin/../lib/gcc/x86_64-cmlfs-linux-musl/10.3.1/../../../../x86_64-cmlfs-linux-musl/bin/ld: /mnt/cmlfs/cgnutools/bin/../../cgnutools/lib/libexecinfo.so.1: undefined reference to `write@GLIBC_2.2.5'
collect2: error: ld returned 1 exit status
make[2]: *** [utils/not/CMakeFiles/not.dir/build.make:98: bin/not] Error 1
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
make[1]: *** [CMakeFiles/Makefile2:13073: utils/not/CMakeFiles/not.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/MsgPackWriter.cpp.o
[ 17%] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/Wasm.cpp.o
[ 17%] Building CXX object lib/BinaryFormat/CMakeFiles/LLVMBinaryFormat.dir/XCOFF.cpp.o
[ 17%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/Record.cpp.o
[ 17%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/SetTheory.cpp.o
[ 17%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/StringMatcher.cpp.o
[ 17%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/TableGenBackend.cpp.o
[ 17%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/TableGenBackendSkeleton.cpp.o
[ 17%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/TGLexer.cpp.o
[ 17%] Linking CXX shared library ../libLLVMOption.so
[ 17%] Linking CXX shared library ../libLLVMBinaryFormat.so
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[ 17%] Built target LLVMOption
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[ 17%] Built target LLVMBinaryFormat
[ 17%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/TGParser.cpp.o
[ 17%] Linking CXX shared library ../libLLVMFileCheck.so
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[ 17%] Built target LLVMFileCheck
[ 17%] Linking CXX shared library ../libLLVMTableGen.so
make[2]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
[ 17%] Built target LLVMTableGen
make[1]: Leaving directory '/mnt/cmlfs/sources/llvm/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/mnt/cmlfs/sources/llvm/build'

**Comment by dslm4515** [comment]
Are you building on a host that uses Glibc instead of musl?

**Comment by dslm4515** [comment]
closing ... master branch uses a new build method. This issue is likely based on previous build method. No branch was mentioned.
