### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by landley** [dslm4515/CMLFS#68]
Tried emailing you but your account doesn't have obvious email address and user@github bounced because of "organizational settings"?

I cloned your "build llvm with musl" repo, but after reading the README I'm not entirely sure how to run the build? It seems to want me to download another one of your projects and... create a chroot to run it in maybe?

I have my own build script that _was_ building a musl-based llvm Hexagon cross compiler (based off the build plumbing the Hexagon guys checked into the kvm test suite: their test involved building a compiler to build their vm image), but when I tried to run it again llvm died trying to link the rtsanitizer code to libc, which obviously didn't exist yet because you need a compiler to build the C library with. (There was also some discussion on the toybox mailing list about this in... July of last year, I think? I can dig up a link if you're curious.)

How do I build your toolchain project, and have you checked for regressions recently?

Rob

**Comment by dslm4515** [comment]
I also am also testing a new design of my s6+s6-rc bootscripts. S6 is hard to develop [for me] due to lack of examples and I couldn't setup a VM to test it faster.

**Comment by landley** [comment]
I'm, um, weird.

https://landley.net/aboriginal/about.html
https://speakerdeck.com/landley/developing-for-non-x86-targets-using-qemu
https://landley.net/toybox/faq.html#mkroot
http://youtu.be/SGmtP5Lg_t0
https://www.youtube.com/watch?v=Sk9TatW9ino

**Comment by dslm4515** [comment]
I admit, CMLFS & MLFS are not for beginners. For CMLFS, begin the build by reading `0-Preparation` in the top level of the repo directory.

I suggest doing a build of LFS first...which can then be used as the host to build CMLFS.
